tests:
  "Toutes les pages sont rapides":
    path: "http://localhost:8000/.*"
    assertions:
    - main.wall_time < 60ms
    - main.memory < 10Mb
  "La page des tâches est rapide":
    path: "http://localhost:8000/tasks"
    assertions:
    - main.wall_time < 60ms
    - main.memory < 10Mb