language: php
php:
  - '7.3'
services:
  - mysql
install:
  - composer install --no-interaction
  - echo "USE mysql;\nUPDATE user SET authentication_string=PASSWORD('') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - php bin/console doctrine:database:create
  - php bin/console doctrine:migration:migrate --no-interaction
script:
   - php bin/console doctrine:fixtures:load -n --env=test
   - php bin/phpunit